In [2]:
import numpy as np
import sys

### 3 benefits of Numpy over python list are:
* Less memory
* Fast
* Convenient

In [3]:
# example showing less memory
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [4]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [5]:
array.size

1000

In [6]:
array.itemsize

4

In [7]:
# example showing less time means fast
import time

In [8]:
size = 1000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [ (x,y) for x,y in zip(l1, l2)]
print('list took time: ',(time.time() - start)*1000)

result = a1 + a2
print('numpy took time: ',(time.time() - start)*1000)



list took time:  0.9992122650146484
numpy took time:  86.99917793273926


# some basic array operations

In [3]:
a = np.array([[1, 2], [3,4], [5,6], [7,8]])

In [6]:
a.ndim

2

In [9]:
a.size

8

In [11]:
a[0]

array([1, 2])

In [12]:
a[0][1]

2

In [14]:
a.itemsize

4

In [17]:
b = np.array([[4, 5, 6], [7, 8, 9]], dtype=np.float64)

In [19]:
b.itemsize

8

In [21]:
a.dtype

dtype('int32')

In [23]:
b.dtype

dtype('float64')

In [25]:
b

array([[4., 5., 6.],
       [7., 8., 9.]])

In [27]:
a.size

8

In [29]:
b.size

6

In [31]:
a.shape

(4, 2)

In [33]:
b.shape

(2, 3)

In [36]:
c = np.array([4, 5, 6], dtype=complex)

In [38]:
c

array([4.+0.j, 5.+0.j, 6.+0.j])

# for placeholder numbers in numpy

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((7,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.arange(1, 4)

array([1, 2, 3])

In [47]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [50]:
# alternative to arange we can use linspace to generate linear space numbers
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
a.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# to flatten array use ravel note ravel function don't touch the original array(same goes to reshape function of array)
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
# to calculate min max in array
a.min()

1

In [68]:
a.max()

8

In [70]:
c = np.array([1, 2])
d = np.array([3, 4])

In [72]:
c +d 

array([4, 6])

In [74]:
c * d

array([3, 8])

In [75]:
c / d

array([0.33333333, 0.5       ])

In [77]:
c.sum()

3

In [79]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [81]:
a.sum()

36

In [83]:
a.sum(axis=0) #summing column wise

array([16, 20])

In [85]:
a.sum(axis=1) #summing row wise

array([ 3,  7, 11, 15])

In [86]:
np.sqrt(a) #calculate square root of each element of array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [87]:
np.std(a) #calculate standard deviation

2.29128784747792

In [89]:
# for doing matrix products
c

array([1, 2])

In [91]:
d

array([3, 4])

In [92]:
c.dot(d)

11

In [93]:
c.vector(d) #look for vector product of matrix multiplication

AttributeError: 'numpy.ndarray' object has no attribute 'vector'

# slicing/stacking arrays, indexing with boolean arrays

In [96]:
e = np.array([[1, 2], [3, 4], [5, 6]])

In [98]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
e[0,1]

2

In [102]:
e[0:3, 1]

array([2, 4, 6])

In [105]:
e[0:3, 0 ]

array([1, 3, 5])

In [108]:
f = np.array([[1,3,4], [33,45,67], [333,54,635]])

In [110]:
f

array([[  1,   3,   4],
       [ 33,  45,  67],
       [333,  54, 635]])

In [113]:
f.ravel()

array([  1,   3,   4,  33,  45,  67, 333,  54, 635])

In [114]:
for i in f:
    print(i)

[1 3 4]
[33 45 67]
[333  54 635]


In [118]:
for i in f.flat:
    print(i)

1
3
4
33
45
67
333
54
635


In [119]:
# vertical and horizontal stacking
g = np.arange(6).reshape(3,2)
h = np.arange(7,13).reshape(3,2)

In [120]:
g

array([[0, 1],
       [2, 3],
       [4, 5]])

In [121]:
h

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [123]:
np.vstack((g,h))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [124]:
np.hstack((g,h))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

# horizontally splitting array

In [125]:
i = np.arange(30).reshape(2, 15)

In [126]:
i

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [130]:
result = np.hsplit(i, 3) #dividing into equal size array

In [131]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [132]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [133]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [135]:
result = np.vsplit(i, 2)

In [136]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [137]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## hands on boolean arrays

In [153]:
j = np.arange(40).reshape(4,10)

In [154]:
j

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [155]:
a = j > 2

In [156]:
a

array([[False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [157]:
j[a]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [158]:
# any element greater than 2, lets just replaced by assigning number 2
j[a] = -2

In [159]:
j

array([[ 0,  1,  2, -2, -2, -2, -2, -2, -2, -2],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2]])

# iterate numpy array using nditer | numpy nditer

In [160]:

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Using normal for loop iteration


In [161]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### For loop with flatten


In [164]:
for cell in a.flatten(): #or a.flat
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


## <center> nditer</center>

## C style ordering

In [165]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


## Fortan style ordering

In [166]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


## external_loop

In [168]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## Modify array values while iterating

In [169]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [170]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

## Iterate two broadcastable arrays concurrently

In [171]:
b = np.arange(3, 15, 4).reshape(3,1)
b


array([[ 3],
       [ 7],
       [11]])

In [172]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
